type: docker
kind: pipeline
name: default

environment:
  GIT_SSL_NO_VERIFY: 'true'

steps:
  - name: build
    image: haskell:9.4.8-slim
    commands:
      - "apt update"
      - "apt install libblas-dev liblapack-dev"
      - "cabal update"
      - "cabal build"